### ISSUE TITLE
Links to ElvUI and ElvUI: Shadow & Light

### ISSUE THREAD

**Issue by jondeans** [Toxicom/toxi-ui#1]
I'm on Mac OSX and the readme links to ElvUI and ElvUI: Shadow and Light both just link to download the TukUI installer for windows (right after a statement that you use wowup.io for install).

It might be more useful to just link directly to the addons themselves, as the rest of the addon links in the list do the same.

ElvUI (https://www.tukui.org/download.php?ui=elvui)
ElvUI: Shadow and Light (https://www.tukui.org/addons.php?id=38)

**Comment by Toxicom** [comment]
Thank you for your insight! Will change that immediately :)
